import { LayoutDashboard, Database, BrainCircuit, GraduationCap, Zap, Shield, BarChart3, Globe, Users, Clock, MessageSquare, Code } from 'lucide-react';
export const NAV_LINKS = [
  { name: 'Home', href: '/' },
  { name: 'Solutions', href: '/solutions' },
  { name: 'Pricing', href: '/pricing' },
  { name: 'About', href: '/about' },
  { name: 'Contact', href: '/contact' },
];
export const SOLUTIONS_DATA = [
  {
    id: 'fm-dashboard',
    title: 'Facilities Command Center',
    category: 'Facilities',
    description: 'Centralized AI-driven dashboard for multi-site property management.',
    icon: LayoutDashboard,
    outcomes: ['30% Reduction in Utility Waste', 'Predictive Maintenance Alerts', 'Live Asset Tracking'],
    pricingHint: 'From R4,500 /pm',
  },
  {
    id: 'smart-inventory',
    title: 'Smart Inventory AI',
    category: 'Business Apps',
    description: 'Automated stock tracking with demand forecasting specifically for SA retailers.',
    icon: Database,
    outcomes: ['Zero Stock-outs', 'Optimal Cash Flow', 'Automated Reordering'],
    pricingHint: 'From R2,900 /pm',
  },
  {
    id: 'customer-neural',
    title: 'Customer Neural Link',
    category: 'AI',
    description: 'Advanced NLP chatbots that handle ZAR currency and local slang natively.',
    icon: BrainCircuit,
    outcomes: ['24/7 Local Support', '80% Query Resolution', 'Lead Qualification'],
    pricingHint: 'From R3,500 /pm',
  },
  {
    id: 'staff-edu-engine',
    title: 'Staff Edu-Engine',
    category: 'Learning',
    description: 'Micro-learning platform for rapid staff upskilling on technical facilities tools.',
    icon: GraduationCap,
    outcomes: ['Faster Onboarding', 'Certification Tracking', 'Compliance Safety'],
    pricingHint: 'From R1,800 /pm',
  },
  {
    id: 'load-shedding-opt',
    title: 'Load-Shedding Optimizer',
    category: 'Facilities',
    description: 'AI logic to schedule energy-heavy tasks around Eskom schedules.',
    icon: Zap,
    outcomes: ['Uninterrupted Operations', 'Battery Life Preservation', 'Cost Savings'],
    pricingHint: 'Included in Enterprise',
  },
  {
    id: 'compliance-vault',
    title: 'POPIA Compliance Vault',
    category: 'Business Apps',
    description: 'Automated data privacy governance for South African business records.',
    icon: Shield,
    outcomes: ['Audit-ready reports', 'Encrypted Storage', 'Breach Prevention'],
    pricingHint: 'From R5,000 /pm',
  },
  {
    id: 'yield-analyst',
    title: 'Revenue Yield Analyst',
    category: 'AI',
    description: 'Predictive pricing models for property rentals and service bookings.',
    icon: BarChart3,
    outcomes: ['15% Revenue Growth', 'Competitor Benchmarking', 'Dynamic Pricing'],
    pricingHint: 'From R6,500 /pm',
  },
  {
    id: 'site-surveyor',
    title: 'Virtual Site Surveyor',
    category: 'Facilities',
    description: 'Image-recognition AI to identify facility damage from mobile photos.',
    icon: Globe,
    outcomes: ['No Travel Required', 'Instant Repair Quotes', 'Historical Audit Trail'],
    pricingHint: 'From R3,200 /pm',
  },
  {
    id: 'hrm-accelerator',
    title: 'HRM Accelerator',
    category: 'Business Apps',
    description: 'Streamlined employee management for shift-based facility workers.',
    icon: Users,
    outcomes: ['Automated Rostering', 'Payroll Integration', 'Leave Management'],
    pricingHint: 'From R2,500 /pm',
  },
  {
    id: 'uptime-monitor',
    title: 'Network Uptime Guard',
    category: 'Facilities',
    description: 'Real-time monitoring of connectivity and solar inverter health.',
    icon: Clock,
    outcomes: ['Immediate Fault Alerts', 'Remote Troubleshooting', 'Historical Analytics'],
    pricingHint: 'From R1,200 /pm',
  },
  {
    id: 'feedback-loop',
    title: 'Customer Feedback Loop',
    category: 'Learning',
    description: 'AI sentiment analysis on customer reviews to drive service improvements.',
    icon: MessageSquare,
    outcomes: ['Brand Reputation Mgmt', 'Actionable Insights', 'Trend Detection'],
    pricingHint: 'From R2,000 /pm',
  },
  {
    id: 'custom-saas',
    title: 'Bespoke SaaS Engine',
    category: 'AI',
    description: 'Custom developed software solutions tailored to your unique workflow.',
    icon: Code,
    outcomes: ['Competitive Edge', 'Seamless Integration', 'Full IP Ownership'],
    pricingHint: 'Custom Quote',
  },
];
export const PRICING_TIERS = [
  {
    name: 'Starter',
    price: 'R4,999',
    description: 'Essential AI tools for small local businesses.',
    features: ['2 Core Solutions', '5 Users Max', 'Standard Email Support', 'Cloud Hosting', 'Monthly Analytics'],
    cta: 'Get Started',
    popular: false,
  },
  {
    name: 'Professional',
    price: 'R12,500',
    description: 'Advanced capabilities for growing enterprises.',
    features: ['6 Core Solutions', 'Unlimited Users', 'Priority 24/7 Support', 'Custom Integrations', 'Weekly Strategy Calls', 'Load-Shedding Optimizer'],
    cta: 'Scale Now',
    popular: true,
  },
  {
    name: 'Enterprise',
    price: 'Custom',
    description: 'Fully bespoke ecosystems for multi-national groups.',
    features: ['All 12 Solutions', 'Dedicated Success Manager', 'On-Premise Deployment Option', 'SLA Guarantees', 'Bespoke Feature Dev'],
    cta: 'Contact Sales',
    popular: false,
  },
];
export const TESTIMONIALS = [
  {
    name: 'Sipho Ndlovu',
    role: 'Operations Director, Cape Logistics',
    text: 'JabulaniFM transformed how we handle load-shedding. Our downtime dropped by 60% in the first month.',
  },
  {
    name: 'Sarah Miller',
    role: 'CEO, Urban Realty',
    text: 'The AI site surveyor is a game changer for our property inspections. Highly recommended.',
  },
];