import { 
  LayoutDashboard, 
  Database, 
  BrainCircuit, 
  GraduationCap, 
  Zap, 
  Shield, 
  BarChart3, 
  Globe, 
  Users, 
  Clock, 
  MessageSquare, 
  Code,
  Cpu,
  Smartphone,
  ShieldCheck,
  LineChart,
  Repeat,
  Video
} from 'lucide-react';
export const NAV_LINKS = [
  { name: 'Home', href: '/' },
  { name: 'Solutions', href: '/solutions' },
  { name: 'Pricing', href: '/pricing' },
  { name: 'About', href: '/about' },
  { name: 'Case Studies', href: '/case-studies' },
  { name: 'Contact', href: '/contact' },
];
export const SOLUTIONS_DATA = [
  // Row 1: Facilities
  {
    id: 'jabulanifm-platform',
    title: 'JabulaniFM Platform',
    category: 'Facilities',
    group: 'Facilities Management SaaS',
    description: 'Our flagship AI PWA designed for the field. Built-in load-shedding logic and POPIA compliance.',
    icon: LayoutDashboard,
    outcomes: ['Real-time Asset Health', 'Automated Work Orders', 'Offline Field Capability'],
    pricingHint: 'R99 - R399 /user/mo',
    hero: true,
  },
  {
    id: 'smart-building',
    title: 'Smart Building Intelligence',
    category: 'Facilities',
    group: 'Facilities Management SaaS',
    description: 'IoT & ESG integration for real-time utility tracking and carbon footprint reporting.',
    icon: Zap,
    outcomes: ['30% Energy Reduction', 'ESG Compliance Ready', 'Automated Metering'],
    pricingHint: 'Custom Quote',
  },
  {
    id: 'portfolio-command',
    title: 'Portfolio Command Center',
    category: 'Facilities',
    group: 'Facilities Management SaaS',
    description: 'Multi-site property management with unified SLA tracking and vendor performance.',
    icon: Globe,
    outcomes: ['Centralized Reporting', 'Vendor SLA Monitoring', 'Lease Management'],
    pricingHint: 'Custom Quote',
  },
  // Row 2: Custom Apps
  {
    id: 'custom-saas',
    title: 'Custom SaaS Platforms',
    category: 'Custom Apps',
    group: 'Custom Business Dashboards',
    description: 'Multi-tenant software with integrated billing and user management for your niche.',
    icon: Code,
    outcomes: ['MVP in 6-8 Weeks', 'Scalable Infrastructure', 'Integrated Payments'],
    pricingHint: 'MVP from R75k',
  },
  {
    id: 'exec-dashboards',
    title: 'Executive Dashboards',
    category: 'Custom Apps',
    group: 'Custom Business Dashboards',
    description: 'High-level KPI visualization for maintenance, finance, and operational teams.',
    icon: BarChart3,
    outcomes: ['Drill-down Analytics', 'Automated Board Reports', 'Mobile-First UI'],
    pricingHint: 'Included in Dev',
  },
  {
    id: 'pwa-apps',
    title: 'Progressive Web Apps',
    category: 'Custom Apps',
    group: 'Custom Business Dashboards',
    description: 'High-performance mobile apps that work offline and load 7x faster than standard sites.',
    icon: Smartphone,
    outcomes: ['Offline-First Tech', 'Push Notifications', 'No App Store Fees'],
    pricingHint: 'Included in Dev',
  },
  // Row 3: AI
  {
    id: 'ai-chatbots',
    title: 'AI Chatbots & Assistants',
    category: 'AI',
    group: 'AI Automation & Compliance',
    description: '24/7 multi-channel NLP agents handling ZAR currency and local customer context.',
    icon: BrainCircuit,
    outcomes: ['80% Query Automation', 'Lead Gen Integration', 'WhatsApp & Web Support'],
    pricingHint: 'R25k setup + R2.5k/mo',
  },
  {
    id: 'process-automation',
    title: 'Business Process Automation',
    category: 'AI',
    group: 'AI Automation & Compliance',
    description: 'RPA and intelligent workflow automation to eliminate manual data entry.',
    icon: Repeat,
    outcomes: ['Zero Manual Errors', 'Audit-Ready Logging', 'Rapid ROI'],
    pricingHint: 'R15k /workflow',
  },
  {
    id: 'predictive-analytics',
    title: 'Predictive Analytics Platforms',
    category: 'AI',
    group: 'AI Automation & Compliance',
    description: 'Forecasting models for property maintenance needs and utility demand planning.',
    icon: LineChart,
    outcomes: ['Preventive Action Triggers', 'Demand Forecasting', 'Risk Mitigation'],
    pricingHint: 'Custom Quote',
  },
  // Row 4: Learning
  {
    id: 'custom-lms',
    title: 'Custom Learning Systems',
    category: 'Learning',
    group: 'Corporate Upskilling',
    description: 'Micro-learning platforms for field staff with low-bandwidth video delivery.',
    icon: GraduationCap,
    outcomes: ['Field Staff Training', 'Certification Tracking', 'Gamified Progress'],
    pricingHint: 'Included in Enterprise',
  },
  {
    id: 'regulatory-vault',
    title: 'Regulatory Compliance Vault',
    category: 'Learning',
    group: 'Corporate Upskilling',
    description: 'Automated governance for POPIA, OHS, and B-BBEE documentation.',
    icon: ShieldCheck,
    outcomes: ['Audit Trail Generation', 'Expiry Alerts', 'Encrypted Storage'],
    pricingHint: 'Included in Enterprise',
  },
  {
    id: 'elearning-content',
    title: 'E-Learning Content Studio',
    category: 'Learning',
    group: 'Corporate Upskilling',
    description: 'Production of SCORM-compliant interactive training modules for technicians.',
    icon: Video,
    outcomes: ['Interactive SCORM', 'Mobile Video Lessons', 'Assessment Engine'],
    pricingHint: 'Included in Enterprise',
  },
];
export const PRICING_TIERS = [
  {
    name: 'Starter',
    price: 'R4,999',
    description: 'Essential Facilities Management tools for local sites.',
    features: [
      'JabulaniFM (Up to 10 Users)',
      'Basic Asset Tracking',
      'POPIA Compliance Vault',
      'Email Support',
      'Monthly Reports'
    ],
    cta: 'Get Started',
    popular: false,
  },
  {
    name: 'Professional',
    price: 'R12,500',
    description: 'Advanced AI and custom SaaS development for growth.',
    features: [
      'Unlimited JabulaniFM Users',
      'Load-Shedding Optimizer',
      'AI Chatbot (Standard)',
      'Custom KPI Dashboards',
      'MVP Dev Discounts',
      'Priority Support'
    ],
    cta: 'Scale Now',
    popular: true,
  },
  {
    name: 'Enterprise',
    price: 'Custom',
    description: 'Fully bespoke ecosystems for national portfolios.',
    features: [
      'Full Custom SaaS Engine',
      'R75k+ MVP Roadmap',
      'Dedicated Success Manager',
      'SLA Guarantees',
      'On-Premise Option',
      'Bespoke AI Training'
    ],
    cta: 'Contact Sales',
    popular: false,
  },
];
export const CASE_STUDIES = [
  {
    id: 'cape-logistics',
    title: 'Cape Logistics',
    metric: '60% Reduction',
    outcome: 'Decrease in operational downtime through AI maintenance forecasting.',
    description: 'By implementing JabulaniFM, Cape Logistics automated their fleet and facility maintenance, surviving Stage 6 load-shedding without missing a delivery.',
    logo: 'SA_LOGISTICS',
  },
  {
    id: 'urban-realty',
    title: 'Urban Realty',
    metric: '400+ Inspections/mo',
    outcome: 'Automated site surveys with 98% accuracy using Image AI.',
    description: 'Urban Realty replaced manual property inspections with our Virtual Surveyor AI, cutting inspection costs by 45% and doubling staff capacity.',
  },
  {
    id: 'pro-tech',
    title: 'Pro-Tech Capital',
    metric: 'R1.2M Saved',
    outcome: 'Annual utility savings through Smart Building Intelligence.',
    description: 'A portfolio-wide rollout of energy-heavy task rescheduling saved Pro-Tech millions in peak-demand penalties.',
  },
];
export const TESTIMONIALS = [
  {
    name: 'Sipho Ndlovu',
    role: 'Operations Director, Cape Logistics',
    text: 'JabulaniFM transformed how we handle load-shedding. Our downtime dropped by 60% in the first month.',
  },
  {
    name: 'Sarah Miller',
    role: 'CEO, Urban Realty',
    text: 'The AI site surveyor is a game changer for our property inspections. Highly recommended.',
  },
];